name: ZombieFight
main: com.dumptruckman.minecraft.zombiefight.ZombieFightPlugin
version: maven-version-number
author: dumptruckman
softdepend: [MobDisguise]

commands:
  zf:
    description: Main plugin command.
    usage: /<command>
  kit:
    description: Lists or selects kits.
    usage: /kit [kit name]