name: ZombieFight
main: com.dumptruckman.minecraft.zombiefight.ZombieFightPlugin
version: 1.1.4
author: dumptruckman
depend: [MobDisguise]

commands:
  zf:
    description: Main plugin command.
    usage: /<command>
  kit:
    description: Lists or selects kits.
    usage: /kit [kit name]